# Generated by Django 3.1.4 on 2020-12-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawlottoapp', '0002_auto_20201222_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottonumber',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
