# Generated by Django 3.1.4 on 2020-12-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawlottoapp', '0005_auto_20201228_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottonumber',
            name='created_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
