# Generated by Django 3.1.4 on 2020-12-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawlottoapp', '0007_remove_lottonumber_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottonumber',
            name='created_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
