# Generated by Django 3.1.4 on 2021-01-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawlottoapp', '0011_lottonumber_lottocount'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottonumber',
            name='created_at2',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
