# Generated by Django 3.1.4 on 2021-01-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawlottoapp', '0013_auto_20210111_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottonumber',
            name='text2',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
