# Generated by Django 3.1.4 on 2021-01-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawlottoapp', '0014_lottonumber_text2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lottonumber',
            name='created_at2',
        ),
        migrations.RemoveField(
            model_name='lottonumber',
            name='text2',
        ),
        migrations.AlterField(
            model_name='lottonumber',
            name='lottocount',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
