# Generated by Django 3.1.4 on 2021-01-11 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawlottoapp', '0016_lottonumber_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lottonumber',
            old_name='test',
            new_name='game',
        ),
    ]
