# Generated by Django 3.1.4 on 2021-01-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawlottoapp', '0017_auto_20210111_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottonumber',
            name='charpoint',
            field=models.IntegerField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lottonumber',
            name='수',
            field=models.IntegerField(max_length=255, null=True),
        ),
    ]
