# Generated by Django 3.1.4 on 2021-01-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawlottoapp', '0021_lottonumber_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottonumber',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
