# Generated by Django 3.1.4 on 2021-01-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawlottoapp', '0022_auto_20210113_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottonumber',
            name='lottocount',
            field=models.IntegerField(null=True),
        ),
    ]
