# Generated by Django 3.1.4 on 2021-01-16 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawlottoapp', '0023_auto_20210113_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottonumber',
            name='charpoint_instance',
            field=models.IntegerField(default=2, null=True),
        ),
        migrations.AlterField(
            model_name='lottonumber',
            name='text',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
