# Generated by Django 3.1.4 on 2021-01-16 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawlottoapp', '0024_auto_20210116_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottonumber',
            name='test',
            field=models.CharField(max_length=255),
        ),
    ]
