# Generated by Django 3.1.4 on 2021-01-16 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawlottoapp', '0026_auto_20210116_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottonumber',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
