# Generated by Django 3.1.4 on 2021-01-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawlottoapp', '0027_auto_20210116_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottonumber',
            name='charpoint',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
