# Generated by Django 3.1.4 on 2021-01-22 22:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawlottoapp', '0030_auto_20210116_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultLotto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), size=7)),
            ],
        ),
    ]
