# Generated by Django 3.1.4 on 2021-01-22 22:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawlottoapp', '0031_resultlotto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultlotto',
            name='result',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), size=None),
        ),
    ]
