# Generated by Django 3.1.4 on 2021-01-24 11:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawlottoapp', '0036_auto_20210124_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultlotto',
            name='lottocountresult',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='resultlotto',
            name='result',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
    ]
