# Generated by Django 3.1.4 on 2021-01-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawlottoapp', '0037_auto_20210124_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultlotto',
            name='result',
        ),
        migrations.AddField(
            model_name='resultlotto',
            name='result1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultlotto',
            name='result2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultlotto',
            name='result3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultlotto',
            name='result4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultlotto',
            name='result5',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultlotto',
            name='result6',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resultlotto',
            name='result7',
            field=models.IntegerField(null=True),
        ),
    ]
