# Generated by Django 3.1.4 on 2021-01-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawlottoapp', '0038_auto_20210124_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottonumber',
            name='test2',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
