# Generated by Django 3.1.4 on 2021-01-24 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawlottoapp', '0041_lottonumber_test4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultlotto',
            old_name='lottocountresult',
            new_name='lottoresult2',
        ),
    ]
