# Generated by Django 3.1.4 on 2021-01-25 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawlottoapp', '0043_remove_resultlotto_lottoresult2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResultLotto',
        ),
    ]
