# Generated by Django 3.1.4 on 2021-01-25 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawlottoapp', '0044_delete_resultlotto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lottonumber',
            name='test2',
        ),
        migrations.RemoveField(
            model_name='lottonumber',
            name='test3',
        ),
        migrations.RemoveField(
            model_name='lottonumber',
            name='test4',
        ),
    ]
