# Generated by Django 3.1.4 on 2021-01-26 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0003_auto_20210113_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='points',
        ),
    ]
